stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: rajdeep015/rajrepo:01
  KUBECONFIG: /tmp/kubeconfig

# Build stage to create the Docker image
build:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main

# Test stage
test:
  stage: test
  image: python:3.9
  services:
    - name: mysql:8
      alias: db
  variables:
    MYSQL_ROOT_PASSWORD: Plmoknijb015
    MYSQL_DATABASE: python
  script:
    - pip install -r requirements.txt
    - python manage.py migrate
    - python manage.py test
  only:
    - main

# Deploy stage
deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  before_script:
    - echo "$KUBECONFIG_CONTENT" | base64 -d > $KUBECONFIG
  script:
    - kubectl apply -f k8s/
  only:
    - main
