apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: django-k8s-deployment

build:
  artifacts:
    - image: rajdeep015/rajrepo # Replace with your Docker image
      context: .
      docker:
        dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml
      - k8s/db.yaml


