apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: rajdeep015/rajrepo:django-app
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              value: "python"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "Plmoknijb015"
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
