apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: rajdeep015/rajrepo:01
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              value: python
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: Plmoknijb015
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "3306"

---
apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
